insert into MOVIES (movie_id, title, genre)values (1, 'Intruder in the Dust', 'Drama');
insert into MOVIES (movie_id, title, genre)values (2, 'Paperboy, The', 'Thriller');
insert into MOVIES (movie_id, title, genre)values (3, 'Rosenstrasse', 'Drama|War');
insert into MOVIES (movie_id, title, genre)values (4, 'Krakatoa, East of Java', 'Adventure|Drama');
insert into MOVIES (movie_id, title, genre)values (5, 'Commare secca, La (Grim Reaper, The)', 'Drama|Mystery');
insert into MOVIES (movie_id, title, genre)values (6, 'Will', 'Children|Drama');
insert into MOVIES (movie_id, title, genre)values (7, 'Grave Secrets (Silent Screams)', 'Horror');
insert into MOVIES (movie_id, title, genre)values (8, 'Insomnia', 'Drama|Mystery|Thriller');
insert into MOVIES (movie_id, title, genre)values (9, 'Pirates of the Caribbean: At World''s End', 'Action|Adventure|Comedy|Fantasy');
insert into MOVIES (movie_id, title, genre)values (10, 'Someone I Loved (Je l''aimais)', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (11, 'Lonesome Dove', 'Adventure|Drama|Western');
insert into MOVIES (movie_id, title, genre)values (12, 'Scavenger Hunt', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (13, 'Muzi v nadeji', 'Comedy|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (14, 'Brokedown Palace', 'Drama');
insert into MOVIES (movie_id, title, genre)values (15, 'Killing of America, The', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (16, 'Disorderly Orderly, The', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (17, 'Upstream', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (18, 'Seven Years Bad Luck', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (19, 'Last Days of Mussolini (Mussolini: Ultimo atto)', 'Drama|War');
insert into MOVIES (movie_id, title, genre)values (20, 'Tristana', 'Drama');
insert into MOVIES (movie_id, title, genre)values (21, 'Legend of the Red Dragon (a.k.a. New Legend of Shaolin, The) (Hong Xi Guan: Zhi Shao Lin wu zu)', 'Action|Adventure|Comedy|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (22, 'The Humanoid', 'Fantasy|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (23, 'Impostors, The', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (24, 'Marnie', 'Drama|Mystery|Romance|Thriller');
insert into MOVIES (movie_id, title, genre)values (25, 'Equinox', 'Adventure|Horror|Mystery');
insert into MOVIES (movie_id, title, genre)values (26, 'Four Times, The (Le Quattro Volte)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (27, 'Taxi', 'Action|Comedy');
insert into MOVIES (movie_id, title, genre)values (28, 'I Want You', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (29, 'Munchies', 'Comedy|Horror');
insert into MOVIES (movie_id, title, genre)values (30, 'King Kong Lives', 'Adventure|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (31, 'Head Above Water', 'Comedy|Thriller');
insert into MOVIES (movie_id, title, genre)values (32, 'Kumail Nanjiani: Beta Male ', 'Comedy|Documentary');
insert into MOVIES (movie_id, title, genre)values (33, 'Invisible Invaders', 'Horror|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (34, 'Le Week-End', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (35, 'Eye of the Needle', 'Thriller');
insert into MOVIES (movie_id, title, genre)values (36, 'Serpico', 'Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (37, '3 Ninjas: High Noon On Mega Mountain', 'Action|Children|Comedy');
insert into MOVIES (movie_id, title, genre)values (38, 'White Nights', 'Drama');
insert into MOVIES (movie_id, title, genre)values (39, 'Evil Bong', 'Comedy|Horror');
insert into MOVIES (movie_id, title, genre)values (40, 'Crazy Heart', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (41, 'Good Marriage, A (Beau mariage, Le)', 'Comedy|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (42, 'Late Chrysanthemums (Bangiku)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (43, 'Grass', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (44, 'Taxidermia', 'Comedy|Drama|Horror');
insert into MOVIES (movie_id, title, genre)values (45, 'Nueba Yol', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (46, 'StreetDance 3D', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (47, 'Encounter in the Third Dimension', 'IMAX');
insert into MOVIES (movie_id, title, genre)values (48, 'Best Man Holiday, The', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (49, 'Just love me (Tylko mnie kochaj)', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (50, 'Jude the Obscure', 'Drama');
insert into MOVIES (movie_id, title, genre)values (51, 'I Like Killing Flies', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (52, 'Anna Karenina', 'Drama');
insert into MOVIES (movie_id, title, genre)values (53, 'Gretchen the Greenhorn', 'Crime|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (54, 'Heartbreak Ridge', 'Action|War');
insert into MOVIES (movie_id, title, genre)values (55, 'Gertie the Dinosaur', 'Animation|Children|Comedy');
insert into MOVIES (movie_id, title, genre)values (56, 'Wrong Man, The', 'Romance|Thriller');
insert into MOVIES (movie_id, title, genre)values (57, 'The 3 Rs', '(no genres listed)');
insert into MOVIES (movie_id, title, genre)values (58, 'Ghost Ship', 'Horror');
insert into MOVIES (movie_id, title, genre)values (59, 'Blink', 'Thriller');
insert into MOVIES (movie_id, title, genre)values (60, 'Wankers, The (Les branleuses)', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (61, 'City of Hope', 'Drama');
insert into MOVIES (movie_id, title, genre)values (62, 'The Raid 2: Berandal', 'Action|Crime|Thriller');
insert into MOVIES (movie_id, title, genre)values (63, 'Three Wishes', 'Drama|Fantasy');
insert into MOVIES (movie_id, title, genre)values (64, 'Cucaracha, La', 'Thriller');
insert into MOVIES (movie_id, title, genre)values (65, 'Lebanon, Pa.', 'Drama');
insert into MOVIES (movie_id, title, genre)values (66, 'When Willie Comes Marching Home', 'Comedy|War');
insert into MOVIES (movie_id, title, genre)values (67, 'Claire of the Moon', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (68, 'Man on the Train (Homme du train, L'')', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (69, 'Tadpole', 'Comedy|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (70, 'Barbarian Queen', 'Action|Adventure|Fantasy');
insert into MOVIES (movie_id, title, genre)values (71, 'Executioners from Shaolin', 'Action|Drama');
insert into MOVIES (movie_id, title, genre)values (72, 'Equus', 'Drama|Mystery');
insert into MOVIES (movie_id, title, genre)values (73, 'Wild Wild West', 'Action|Comedy|Sci-Fi|Western');
insert into MOVIES (movie_id, title, genre)values (74, 'Hound of the Baskervilles, The', 'Crime|Horror|Mystery');
insert into MOVIES (movie_id, title, genre)values (75, 'Woyzeck', 'Drama');
insert into MOVIES (movie_id, title, genre)values (76, 'Reefer Madness: The Movie Musical', 'Comedy|Drama|Musical');
insert into MOVIES (movie_id, title, genre)values (77, 'Along Came Jones', 'Comedy|Romance|Western');
insert into MOVIES (movie_id, title, genre)values (78, 'Larceny, Inc.', 'Comedy|Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (79, 'Cinderella', 'Animation|Children|Fantasy|Musical|Romance');
insert into MOVIES (movie_id, title, genre)values (80, 'L: Change the World', 'Crime|Drama|Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (81, 'Debutantes, Los', 'Crime|Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (82, 'Waste Land', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (83, 'Spider-Man: The Ultimate Villain Showdown', 'Animation');
insert into MOVIES (movie_id, title, genre)values (84, 'Bobby Jones, Stroke of Genius', 'Drama');
insert into MOVIES (movie_id, title, genre)values (85, 'First Texan, The', 'Western');
insert into MOVIES (movie_id, title, genre)values (86, 'Bang the Drum Slowly', 'Drama');
insert into MOVIES (movie_id, title, genre)values (87, 'Kid, The', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (88, 'Other Shore, The', 'Adventure|Documentary');
insert into MOVIES (movie_id, title, genre)values (89, 'Parent Trap, The', 'Children|Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (90, 'The Linguists', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (91, 'Trouble with Dee Dee, The', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (92, 'Tropico', 'Drama|Fantasy|Romance');
insert into MOVIES (movie_id, title, genre)values (93, 'Dragon Hunters (Chasseurs de dragons)', 'Adventure|Animation|Children');
insert into MOVIES (movie_id, title, genre)values (94, 'My Name Is Bruce', 'Comedy|Horror');
insert into MOVIES (movie_id, title, genre)values (95, 'Evolution', 'Comedy|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (96, '12th & Delaware', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (97, 'She No Longer Talks, She Shoots', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (98, 'Canciones de amor en Lolita''s Club', 'Drama');
insert into MOVIES (movie_id, title, genre)values (99, 'Warning from Space (Uchûjin Tôkyô ni arawaru)', 'Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (100, 'Silent Light (Stellet licht)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (101, 'The Apocalypse', 'Action|Drama');
insert into MOVIES (movie_id, title, genre)values (102, 'Greater Promise, A (Iskateli Schastya)', 'Crime|Drama|Western');
insert into MOVIES (movie_id, title, genre)values (103, 'Cast Away', 'Drama');
insert into MOVIES (movie_id, title, genre)values (104, 'Rainmaker, The', 'Drama');
insert into MOVIES (movie_id, title, genre)values (105, 'Electric House, The', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (106, 'Love Games', 'Animation|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (107, 'My Awkward Sexual Adventure', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (108, 'Agronomist, The', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (109, 'Virginity Hit, The', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (110, 'Love Is a Many-Splendored Thing', 'Drama|Romance|War');
insert into MOVIES (movie_id, title, genre)values (111, 'Race to Witch Mountain', 'Adventure|Children|Fantasy|Sci-Fi|Thriller');
insert into MOVIES (movie_id, title, genre)values (112, 'Godfather: Part III, The', 'Crime|Drama|Mystery|Thriller');
insert into MOVIES (movie_id, title, genre)values (113, 'House That Dripped Blood, The', 'Horror|Mystery');
insert into MOVIES (movie_id, title, genre)values (114, 'Oliver Twist', 'Adventure|Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (115, 'Watchmen: Tales of the Black Freighter', 'Action|Adventure|Animation|Horror');
insert into MOVIES (movie_id, title, genre)values (116, 'Return to Lonesome Dove', 'Drama|Western');
insert into MOVIES (movie_id, title, genre)values (117, 'Cargo', 'Adventure|Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (118, 'Wrong Man, The', 'Romance|Thriller');
insert into MOVIES (movie_id, title, genre)values (119, 'Helen of Troy', 'Action|Adventure|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (120, 'Lonely Are the Brave', 'Drama|Western');
insert into MOVIES (movie_id, title, genre)values (121, 'Blue', 'Drama');
insert into MOVIES (movie_id, title, genre)values (122, 'The Stoker', 'Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (123, '7 Below (Seven Below)', 'Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (124, 'Idle Class, The', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (125, 'Pippi in the South Seas (Pippi Långstrump på de sju haven)', 'Adventure|Children');
insert into MOVIES (movie_id, title, genre)values (126, 'Rosario Tijeras', 'Crime|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (127, 'Please Give', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (128, 'Lady Death', 'Action|Animation|Horror');
insert into MOVIES (movie_id, title, genre)values (129, 'Two Women (Ciociara, La)', 'Drama|War');
insert into MOVIES (movie_id, title, genre)values (130, 'Critical Condition', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (131, 'Chambermaid on the Titanic, The (Femme de chambre du Titanic, La)', 'Romance');
insert into MOVIES (movie_id, title, genre)values (132, 'Elstree Calling', 'Comedy|Musical');
insert into MOVIES (movie_id, title, genre)values (133, 'Kung Pow: Enter the Fist', 'Action|Comedy');
insert into MOVIES (movie_id, title, genre)values (134, 'Black Dog', 'Action|Thriller');
insert into MOVIES (movie_id, title, genre)values (135, 'Grace of My Heart', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (136, 'Margaret', 'Drama');
insert into MOVIES (movie_id, title, genre)values (137, 'Mass Transit', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (138, 'Sound of Fury, The', 'Crime|Drama|Film-Noir');
insert into MOVIES (movie_id, title, genre)values (139, 'Mississippi Masala', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (140, 'Classe américaine, La (a.k.a. Le grand détournement)', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (141, 'Crossing Guard, The', 'Action|Crime|Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (142, 'Asterix and Cleopatra (Astérix et Cléopâtre)', 'Action|Adventure|Animation|Children|Comedy');
insert into MOVIES (movie_id, title, genre)values (143, 'In Your Dreams (Dans tes rêves)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (144, 'Wedding in Blood (Noces rouges, Les)', 'Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (145, 'Kings of Pastry (Les rois de la pâtisserie)', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (146, 'Boys from Brazil, The', 'Action|Mystery|Thriller');
insert into MOVIES (movie_id, title, genre)values (147, 'The Hobbit: The Battle of the Five Armies', 'Adventure|Fantasy');
insert into MOVIES (movie_id, title, genre)values (148, 'Christine Jorgensen Story, The', 'Drama');
insert into MOVIES (movie_id, title, genre)values (149, 'Parasomnia', 'Horror|Romance|Thriller');
insert into MOVIES (movie_id, title, genre)values (150, 'Sorcerer', 'Action|Thriller');
insert into MOVIES (movie_id, title, genre)values (151, 'Web of Death, The', 'Action|Adventure|Fantasy|Horror');
insert into MOVIES (movie_id, title, genre)values (152, 'Turn of the Screw, The', 'Drama|Horror|Mystery');
insert into MOVIES (movie_id, title, genre)values (153, 'My Son, My Son, What Have Ye Done', 'Drama|Horror');
insert into MOVIES (movie_id, title, genre)values (154, 'Gestapo''s Last Orgy, The (L''ultima orgia del III Reich)', 'Thriller|War');
insert into MOVIES (movie_id, title, genre)values (155, 'Woman in the Moon (By Rocket to the Moon) (Frau im Mond)', 'Comedy|Drama|Romance|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (156, 'A.K.', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (157, 'John Carter', 'Action|Adventure|Sci-Fi|IMAX');
insert into MOVIES (movie_id, title, genre)values (158, 'Jerusalema (Gangster''s Paradise: Jerusalema)', 'Action|Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (159, 'Lost Honor of Katharina Blum, The (Verlorene Ehre der Katharina Blum oder: Wie Gewalt entstehen und wohin sie führen kann, Die)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (160, 'Winter Sleepers (Winterschläfer)', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (161, 'Blood and Black Lace (Sei donne per l''assassino)', 'Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (162, 'Mechanic, The', 'Action|Thriller');
insert into MOVIES (movie_id, title, genre)values (163, 'Secuestrados (Kidnapped)', 'Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (164, 'Finder''s Fee', 'Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (165, 'Voodoo Dawn', 'Horror');
insert into MOVIES (movie_id, title, genre)values (166, 'Obvious Child', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (167, 'Happily N''Ever After', 'Animation|Children|Comedy');
insert into MOVIES (movie_id, title, genre)values (168, 'Happy Gilmore', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (169, 'Calendar', 'Drama');
insert into MOVIES (movie_id, title, genre)values (170, 'Damage (Fatale)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (171, 'Septième juré, Le', 'Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (172, 'Rugrats Movie, The', 'Animation|Children|Comedy');
insert into MOVIES (movie_id, title, genre)values (173, 'Burning Hot Summer, A (Un été brûlant)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (174, 'Scarlet Street', 'Film-Noir');
insert into MOVIES (movie_id, title, genre)values (175, 'Rambo: First Blood Part II', 'Action|Adventure|Thriller');
insert into MOVIES (movie_id, title, genre)values (176, 'Tale of the Wind, A (Histoire de vent, Une)', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (177, 'Marathon Family, The (Maratonci Trce Pocasni Krug)', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (178, 'Love Letter ', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (179, 'On the Rumba River (On the Rhumba River)', 'Documentary|Musical');
insert into MOVIES (movie_id, title, genre)values (180, 'Perfect', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (181, 'Looney Tunes: Back in Action', 'Action|Animation|Children|Fantasy');
insert into MOVIES (movie_id, title, genre)values (182, 'Good Dick', 'Comedy|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (183, 'Hands Off the Loot (Touchez pas au grisbi)', 'Crime|Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (184, 'Italianamerican', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (185, '25th Hour', 'Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (186, 'Black Hawk Down', 'Action|Drama|War');
insert into MOVIES (movie_id, title, genre)values (187, 'Nightfall', 'Crime|Drama|Film-Noir');
insert into MOVIES (movie_id, title, genre)values (188, '1', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (189, 'Capture of Bigfoot, The', 'Adventure|Horror|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (190, 'Androcles and the Lion', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (191, 'Someone Like You (Unnaipol Oruvan)', 'Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (192, 'Walker, The', 'Drama|Mystery');
insert into MOVIES (movie_id, title, genre)values (193, 'Last Days on Mars, The', 'Horror|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (194, 'Puppet Master II', 'Horror|Sci-Fi|Thriller');
insert into MOVIES (movie_id, title, genre)values (195, 'Cape No. 7 (Hái-kak chhit-ho)', 'Comedy|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (196, 'Reel Bad Arabs: How Hollywood Vilifies a People', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (197, 'Talk to Me', 'Drama');
insert into MOVIES (movie_id, title, genre)values (198, 'Odette Toulemonde', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (199, 'Flight That Fought Back, The', 'Drama');
insert into MOVIES (movie_id, title, genre)values (200, 'Forgetting the Girl', 'Drama');
insert into MOVIES (movie_id, title, genre)values (201, 'Gappa: The Triphibian Monsters (AKA Monster from a Prehistoric Planet) (Daikyojû Gappa)', 'Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (202, 'Silence, The (Tystnaden)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (203, 'Tennessee Johnson', 'Drama');
insert into MOVIES (movie_id, title, genre)values (204, 'Pear Tree, The (Derakhte Golabi)', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (205, 'Twilight Zone: The Movie', 'Fantasy|Horror|Sci-Fi|Thriller');
insert into MOVIES (movie_id, title, genre)values (206, 'Lake Tahoe', 'Drama');
insert into MOVIES (movie_id, title, genre)values (207, 'Hedgehog, The (Le hérisson)', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (208, 'Equalizer, The', 'Action|Crime|Thriller');
insert into MOVIES (movie_id, title, genre)values (209, 'Candidate, The (Kandidaten)', 'Thriller');
insert into MOVIES (movie_id, title, genre)values (210, 'Wife, The', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (211, 'Boundin''', 'Animation|Children');
insert into MOVIES (movie_id, title, genre)values (212, 'Bad News Bears in Breaking Training, The', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (213, 'Curse of the Golden Flower (Man cheng jin dai huang jin jia)', 'Action|Drama');
insert into MOVIES (movie_id, title, genre)values (214, 'Blue Kite, The (Lan feng zheng)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (215, 'Monster X Strikes Back: Attack the G8 Summit, The (Girara no gyakushû: Tôya-ko Samitto kikiippatsu)', 'Comedy|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (216, 'Legally Blonde 2: Red, White & Blonde', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (217, 'Trouble with the Truth, The', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (218, 'Lost in Yonkers', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (219, 'Bedtime Story', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (220, 'Before I Go to Sleep', 'Mystery|Thriller');
insert into MOVIES (movie_id, title, genre)values (221, 'Passionate Friends, The (a.k.a. One Woman''s Story)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (222, 'City Slickers', 'Comedy|Western');
insert into MOVIES (movie_id, title, genre)values (223, 'Springtime in a Small Town (Xiao cheng zhi chun)', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (224, 'Zombie Island Massacre', 'Horror');
insert into MOVIES (movie_id, title, genre)values (225, 'Tokyo Joe', 'Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (226, 'Bloodsuckers', 'Action|Horror|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (227, 'Paris-Manhattan', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (228, 'Danton', 'Drama');
insert into MOVIES (movie_id, title, genre)values (229, 'Hamlet', 'Crime|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (230, 'Red Angel (Akai tenshi)', 'Drama|Romance|War');
insert into MOVIES (movie_id, title, genre)values (231, 'Vidal Sassoon: The Movie', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (232, 'Felicity', 'Drama');
insert into MOVIES (movie_id, title, genre)values (233, 'Torrente 5: Operación Eurovegas', 'Action|Comedy');
insert into MOVIES (movie_id, title, genre)values (234, 'Photographer (Fotoamator)', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (235, 'Stella', 'Drama');
insert into MOVIES (movie_id, title, genre)values (236, 'Ong-Bak 3: The Final Battle (Ong Bak 3)', 'Action');
insert into MOVIES (movie_id, title, genre)values (237, 'Jason and the Argonauts', 'Action|Adventure|Fantasy');
insert into MOVIES (movie_id, title, genre)values (238, '29 Palms', 'Comedy|Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (239, 'Last Exit to Brooklyn', 'Drama');
insert into MOVIES (movie_id, title, genre)values (240, 'Cabin Fever', 'Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (241, 'Mr. Warmth: The Don Rickles Project', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (242, 'Casey Jones', 'Action|Adventure|Fantasy');
insert into MOVIES (movie_id, title, genre)values (243, 'Guns of Fort Petticoat, The', 'War|Western');
insert into MOVIES (movie_id, title, genre)values (244, 'Arrival, The', 'Action|Sci-Fi|Thriller');
insert into MOVIES (movie_id, title, genre)values (245, 'Sazen Tange and the Pot Worth a Million Ryo', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (246, 'Schindler''s List', 'Drama|War');
insert into MOVIES (movie_id, title, genre)values (247, 'Soup to Nuts', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (248, 'Sound City', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (249, 'Mr. Kinky', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (250, 'All That... for This?!', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (251, 'Seconds', 'Mystery|Sci-Fi|Thriller');
insert into MOVIES (movie_id, title, genre)values (252, 'Bodyguard, The (Karate Kiba)', 'Action|Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (253, 'In the House', 'Comedy|Drama|Mystery|Thriller');
insert into MOVIES (movie_id, title, genre)values (254, 'Rack, The', 'Drama|War');
insert into MOVIES (movie_id, title, genre)values (255, 'Since Otar Left (Depuis qu''Otar est parti...)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (256, 'Great Guy', 'Crime|Drama|Mystery');
insert into MOVIES (movie_id, title, genre)values (257, 'Sin of Madelon Claudet, The', 'Drama');
insert into MOVIES (movie_id, title, genre)values (258, 'Librarian: Quest for the Spear, The', 'Action|Adventure|Comedy|Fantasy|Romance');
insert into MOVIES (movie_id, title, genre)values (259, 'Breathless (À bout de souffle)', 'Crime|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (260, 'Driven', 'Action|Thriller');
insert into MOVIES (movie_id, title, genre)values (261, 'La nación clandestina', 'Drama');
insert into MOVIES (movie_id, title, genre)values (262, 'Message to Love: The Isle of Wight Festival', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (263, 'Entity, The', 'Horror');
insert into MOVIES (movie_id, title, genre)values (264, 'Warriors of Heaven and Earth (Tian di ying xiong)', 'Action|Adventure|Drama');
insert into MOVIES (movie_id, title, genre)values (265, 'House of Branching Love, The (Haarautuvan rakkauden talo)', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (266, 'Land of the Blind', 'Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (267, 'Liebelei', 'Romance');
insert into MOVIES (movie_id, title, genre)values (268, 'Mitt', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (269, 'Waitress', 'Comedy|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (270, 'Assassination Bureau, The', 'Action|Adventure|Comedy|Crime|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (271, 'Seraphim Falls', 'Action|Adventure|Drama|War|Western');
insert into MOVIES (movie_id, title, genre)values (272, 'Ernest Goes to Jail', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (273, 'Janky Promoters, The', 'Comedy|Crime|Musical');
insert into MOVIES (movie_id, title, genre)values (274, 'Two Deaths', 'Drama');
insert into MOVIES (movie_id, title, genre)values (275, '2 ou 3 choses que je sais d''elle (2 or 3 Things I Know About Her)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (276, 'Too Many Husbands', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (277, 'Robin-B-Hood (Bo bui gai wak)', 'Action|Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (278, 'Twilight Zone: The Movie', 'Fantasy|Horror|Sci-Fi|Thriller');
insert into MOVIES (movie_id, title, genre)values (279, 'Kaboom', 'Comedy|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (280, 'Vampire Hunter D: Bloodlust (Banpaia hantâ D)', 'Animation|Fantasy|Horror|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (281, 'Hell to Eternity', 'Drama|War');
insert into MOVIES (movie_id, title, genre)values (282, 'Night Shift', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (283, 'Bangkok Dangerous', 'Action|Crime|Romance');
insert into MOVIES (movie_id, title, genre)values (284, 'Scooby-Doo 2: Monsters Unleashed', 'Action|Adventure|Children|Comedy|Mystery');
insert into MOVIES (movie_id, title, genre)values (285, 'Miss Sweden (Fröken Sverige)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (286, 'Densha otoko (Train Man)', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (287, 'Young and Prodigious T.S. Spivet, The (L''extravagant voyage du jeune et prodigieux T.S. Spivet)', 'Adventure|Children|Drama');
insert into MOVIES (movie_id, title, genre)values (288, 'Catfish in Black Bean Sauce', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (289, 'Box, The', 'Drama|Horror|Mystery|Sci-Fi|Thriller');
insert into MOVIES (movie_id, title, genre)values (290, 'Congo', 'Action|Adventure|Mystery|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (291, 'Prophecy II, The', 'Horror');
insert into MOVIES (movie_id, title, genre)values (292, 'China Syndrome, The', 'Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (293, 'Conspiracy', 'Action|Drama|Mystery|Thriller|War');
insert into MOVIES (movie_id, title, genre)values (294, 'Japanese Girls at the Harbor (Minato no nihon musume)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (295, 'Cube of Sugar, A (Ye Habe Ghand)', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (296, 'Mitt', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (297, 'War Lord, The', 'Drama|Romance|War');
insert into MOVIES (movie_id, title, genre)values (298, 'Get Out of My Room', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (299, 'Thin Man Goes Home, The', 'Comedy|Crime|Mystery');
insert into MOVIES (movie_id, title, genre)values (300, 'Transcendence', 'Drama|Sci-Fi|IMAX');
insert into MOVIES (movie_id, title, genre)values (301, 'Mimic 2', 'Horror|Sci-Fi|Thriller');
insert into MOVIES (movie_id, title, genre)values (302, 'Dirty Money (Un flic)', 'Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (303, 'January Man, The', 'Comedy|Crime|Mystery|Thriller');
insert into MOVIES (movie_id, title, genre)values (304, 'Dallas Buyers Club', 'Drama');
insert into MOVIES (movie_id, title, genre)values (305, 'Christmas Story 2, A', 'Children|Comedy');
insert into MOVIES (movie_id, title, genre)values (306, 'Operation Mad Ball', 'Comedy|War');
insert into MOVIES (movie_id, title, genre)values (307, 'Eye for an Eye, An (Oeil pour oeil) (Eyes of the Sahara)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (308, 'MC5*: A True Testimonial', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (309, 'Robin and Marian', 'Adventure|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (310, 'Thanksgiving Family Reunion (National Lampoon''s Holiday Reunion)', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (311, 'Pleasures of the Flesh (Etsuraku)', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (312, 'The Sea Vultures', 'Drama');
insert into MOVIES (movie_id, title, genre)values (313, 'Zero de conduite (Zero for Conduct) (Zéro de conduite: Jeunes diables au collège)', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (314, 'Beauty of the Day (Belle de jour)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (315, 'Dark City', 'Adventure|Film-Noir|Sci-Fi|Thriller');
insert into MOVIES (movie_id, title, genre)values (316, 'Single White Female 2: The Psycho', 'Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (317, 'Undisputed III: Redemption', 'Action|Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (318, 'Landscape Suicide', 'Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (319, 'Mischief', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (320, 'Eastwood on Eastwood', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (321, 'Buddy', 'Adventure|Children|Drama');
insert into MOVIES (movie_id, title, genre)values (322, 'Seems Like Old Times', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (323, 'Female Vampire (Les avaleuses) (Erotic Kill)', 'Horror');
insert into MOVIES (movie_id, title, genre)values (324, 'Freeway II: Confessions of a Trickbaby', 'Comedy|Crime|Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (325, 'Earth (Zemlya)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (326, 'Eichmann', 'Drama|War');
insert into MOVIES (movie_id, title, genre)values (327, 'Gamera vs. Gyaos (Daikaijû kûchûsen: Gamera tai Gyaosu)', 'Action|Horror|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (328, 'Babylon 5: The River of Souls', 'Drama|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (329, 'Most Beautiful, The (Ichiban utsukushiku)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (330, 'War of the Wildcats (In Old Oklahoma)', 'Western');
insert into MOVIES (movie_id, title, genre)values (331, 'Cut', 'Comedy|Horror|Mystery|Thriller');
insert into MOVIES (movie_id, title, genre)values (332, 'Cold Mountain', 'Drama|Romance|War');
insert into MOVIES (movie_id, title, genre)values (333, 'First Men in the Moon', 'Adventure|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (334, 'Where Angels Go, Trouble Follows', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (335, 'House on Telegraph Hill, The', 'Drama|Film-Noir|Mystery|Thriller');
insert into MOVIES (movie_id, title, genre)values (336, 'That Certain Summer', 'Drama');
insert into MOVIES (movie_id, title, genre)values (337, 'Orlando', 'Drama|Fantasy|Romance');
insert into MOVIES (movie_id, title, genre)values (338, 'Letter, The (La lettre)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (339, 'Hair Show', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (340, 'The Perils of Pauline', '(no genres listed)');
insert into MOVIES (movie_id, title, genre)values (341, 'Protocols of Zion', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (342, 'Marley & Me', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (343, 'Water-mirror of Granada', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (344, 'Saw III', 'Crime|Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (345, 'In Harm''s Way', 'Drama|War');
insert into MOVIES (movie_id, title, genre)values (346, 'Honeymooners, The', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (347, 'Eye See You (D-Tox)', 'Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (348, 'Tokyo Fiancée', '(no genres listed)');
insert into MOVIES (movie_id, title, genre)values (349, 'Nell', 'Drama');
insert into MOVIES (movie_id, title, genre)values (350, 'Raise Your Voice', 'Romance');
insert into MOVIES (movie_id, title, genre)values (351, 'Drained (O cheiro do Ralo)', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (352, 'Skylark', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (353, 'Girl Play', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (354, 'Three O''Clock High', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (355, 'Soul Men', 'Comedy|Musical');
insert into MOVIES (movie_id, title, genre)values (356, 'Alex Cross', 'Action|Crime|Mystery|Thriller');
insert into MOVIES (movie_id, title, genre)values (357, 'Snow on the Pines, The', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (358, 'Idle Mist (Vana Espuma)', 'Crime|Horror|Mystery|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (359, 'Gloria', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (360, 'Wrong Side Up (Pribehy obycejneho silenstvi)', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (361, 'Stiff Upper Lips', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (362, 'Evil That Men Do, The', 'Action|Thriller');
insert into MOVIES (movie_id, title, genre)values (363, 'Internes Can''t Take Money', 'Crime|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (364, 'Petits Freres (Petits Frères)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (365, 'Flushed Away', 'Animation|Comedy');
insert into MOVIES (movie_id, title, genre)values (366, 'Thousand Months, A (Mille mois)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (367, 'Halloween is Grinch Night', 'Animation|Children');
insert into MOVIES (movie_id, title, genre)values (368, 'Red Sonja', 'Action|Adventure|Fantasy');
insert into MOVIES (movie_id, title, genre)values (369, 'Before Midnight', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (370, 'Trouble Bound', 'Action|Comedy');
insert into MOVIES (movie_id, title, genre)values (371, 'Canyons, The', 'Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (372, 'Another Year', 'Drama');
insert into MOVIES (movie_id, title, genre)values (373, 'Rush Hour 2', 'Action|Comedy');
insert into MOVIES (movie_id, title, genre)values (374, 'Virginia City', 'Action|Drama|Romance|Western');
insert into MOVIES (movie_id, title, genre)values (375, 'a/k/a Tommy Chong', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (376, 'Monkey Shines', 'Horror|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (377, 'Amityville 3-D', 'Horror');
insert into MOVIES (movie_id, title, genre)values (378, 'Mockingbird Don''t Sing', 'Drama');
insert into MOVIES (movie_id, title, genre)values (379, 'Shadows of Our Forgotten Ancestors (Tini zabutykh predkiv)', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (380, 'Winter Nomads', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (381, 'Circle of Iron', 'Action|Adventure|Fantasy|Mystery');
insert into MOVIES (movie_id, title, genre)values (382, 'Papa', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (383, 'Rollerball', 'Action|Drama|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (384, 'Lizard in a Woman''s Skin, A (Lucertola con la pelle di donna, Una)', 'Horror|Mystery|Thriller');
insert into MOVIES (movie_id, title, genre)values (385, 'Fast Times at Ridgemont High', 'Comedy|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (386, 'Spirit Trap', 'Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (387, 'Balzac and the Little Chinese Seamstress (Xiao cai feng)', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (388, 'This World, Then the Fireworks', 'Crime|Drama|Film-Noir');
insert into MOVIES (movie_id, title, genre)values (389, 'Hunger Games: Catching Fire, The', 'Action|Adventure|Sci-Fi|IMAX');
insert into MOVIES (movie_id, title, genre)values (390, 'Blood Shot', 'Action|Comedy|Horror');
insert into MOVIES (movie_id, title, genre)values (391, 'Off the Charts: The Song-Poem Story', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (392, 'Stargate', 'Action|Adventure|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (393, 'Privates on Parade', 'Comedy|Drama|War');
insert into MOVIES (movie_id, title, genre)values (394, 'Outlaw Josey Wales, The', 'Action|Adventure|Drama|Thriller|Western');
insert into MOVIES (movie_id, title, genre)values (395, 'Unbreakable', 'Drama|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (396, 'Spy Next Door, The', 'Action|Children|Comedy');
insert into MOVIES (movie_id, title, genre)values (397, '11 Flowers (Wo 11)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (398, 'Thin Line Between Love and Hate, A', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (399, 'Family Man, The', 'Comedy|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (400, 'Wonderland', 'Drama');
insert into MOVIES (movie_id, title, genre)values (401, 'Wild Horses (Caballos salvajes)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (402, 'Cosmopolis', 'Drama');
insert into MOVIES (movie_id, title, genre)values (403, 'Champ, The', 'Drama');
insert into MOVIES (movie_id, title, genre)values (404, 'One Mile Away', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (405, 'Man from Monterey, The', 'Western');
insert into MOVIES (movie_id, title, genre)values (406, 'Animal Crackers', 'Comedy|Musical');
insert into MOVIES (movie_id, title, genre)values (407, 'Hellraiser: Hellseeker', 'Horror');
insert into MOVIES (movie_id, title, genre)values (408, 'La Bandera', '(no genres listed)');
insert into MOVIES (movie_id, title, genre)values (409, 'After Death (Posle smerti)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (410, 'Invitation to Happiness', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (411, 'G.I. Joe: The Rise of Cobra', 'Action|Adventure|Sci-Fi|Thriller');
insert into MOVIES (movie_id, title, genre)values (412, 'Sallah', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (413, 'Fantomas vs. Scotland Yard', 'Adventure|Comedy|Crime|Fantasy');
insert into MOVIES (movie_id, title, genre)values (414, 'Shaft, The (a.k.a. Down)', 'Action|Horror|Mystery|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (415, 'Love Happens', 'Comedy|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (416, 'Wolf', 'Crime|Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (417, 'Walk, Don''t Run', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (418, 'Heckler', 'Comedy|Documentary');
insert into MOVIES (movie_id, title, genre)values (419, 'Breaking Point, The', 'Crime|Drama|Film-Noir');
insert into MOVIES (movie_id, title, genre)values (420, 'Väreitä', 'Drama');
insert into MOVIES (movie_id, title, genre)values (421, 'Encounter in the Third Dimension', 'IMAX');
insert into MOVIES (movie_id, title, genre)values (422, 'Doctor Strange', 'Action|Animation|Children|Fantasy|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (423, 'Lawnmower Man, The', 'Action|Horror|Sci-Fi|Thriller');
insert into MOVIES (movie_id, title, genre)values (424, 'Ping Pong', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (425, 'Faraway, So Close (In weiter Ferne, so nah!)', 'Drama|Fantasy|Mystery|Romance');
insert into MOVIES (movie_id, title, genre)values (426, 'War on Democracy, The', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (427, 'Talk of Angels', 'Drama');
insert into MOVIES (movie_id, title, genre)values (428, 'Nowhere in Africa (Nirgendwo in Afrika)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (429, 'Fear, The', 'Horror');
insert into MOVIES (movie_id, title, genre)values (430, 'Perfect Sisters', 'Drama|Mystery');
insert into MOVIES (movie_id, title, genre)values (431, 'Alice', 'Comedy|Drama|Fantasy|Romance');
insert into MOVIES (movie_id, title, genre)values (432, 'Into the Woods', 'Adventure|Comedy|Fantasy|Musical');
insert into MOVIES (movie_id, title, genre)values (433, 'Adventures of Don Juan', 'Adventure|Romance');
insert into MOVIES (movie_id, title, genre)values (434, 'To Be or Not to Be', 'Comedy|Drama|War');
insert into MOVIES (movie_id, title, genre)values (435, 'Terror on a Train (Time Bomb)', 'Thriller');
insert into MOVIES (movie_id, title, genre)values (436, 'Once My Mother', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (437, 'Teenage Mutant Ninja Turtles III', 'Action|Adventure|Children|Comedy|Fantasy');
insert into MOVIES (movie_id, title, genre)values (438, 'Aloft', 'Drama');
insert into MOVIES (movie_id, title, genre)values (439, 'Lilies', 'Drama|Fantasy|Romance');
insert into MOVIES (movie_id, title, genre)values (440, 'Big Fix, The', 'Comedy|Mystery|Thriller');
insert into MOVIES (movie_id, title, genre)values (441, 'Ju-on: White Ghost', 'Horror');
insert into MOVIES (movie_id, title, genre)values (442, 'Ring of Bright Water', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (443, 'Jive Turkey', 'Action');
insert into MOVIES (movie_id, title, genre)values (444, 'Cup, The (Phörpa)', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (445, 'Excuse My Dust', 'Comedy|Musical');
insert into MOVIES (movie_id, title, genre)values (446, 'Reformer and the Redhead, The', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (447, 'Black Dawn', 'Action');
insert into MOVIES (movie_id, title, genre)values (448, 'Accused, The', 'Drama');
insert into MOVIES (movie_id, title, genre)values (449, 'Nude for Satan (Nuda per Satana)', 'Horror');
insert into MOVIES (movie_id, title, genre)values (450, 'Blood and Black Lace (Sei donne per l''assassino)', 'Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (451, 'One Crazy Summer', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (452, 'Defenseless', 'Thriller');
insert into MOVIES (movie_id, title, genre)values (453, 'Study in Terror, A', 'Crime|Drama|Horror');
insert into MOVIES (movie_id, title, genre)values (454, 'Last Exorcism Part II, The', 'Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (455, 'Keep Your Distance', 'Drama|Mystery|Romance');
insert into MOVIES (movie_id, title, genre)values (456, 'Captain''s Paradise, The', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (457, 'Book of Life, The', 'Comedy|Fantasy');
insert into MOVIES (movie_id, title, genre)values (458, 'Truth, The ', 'Thriller');
insert into MOVIES (movie_id, title, genre)values (459, 'Official Story, The (La historia oficial)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (460, 'Broadway Idiot', 'Documentary|Musical');
insert into MOVIES (movie_id, title, genre)values (461, 'Band Wagon, The', 'Comedy|Musical');
insert into MOVIES (movie_id, title, genre)values (462, 'Spaced Invaders', 'Adventure|Comedy|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (463, 'Good Night to Die, A', 'Action|Comedy|Crime|Thriller');
insert into MOVIES (movie_id, title, genre)values (464, 'Vampires Suck', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (465, 'All That... for This?!', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (466, 'State of Grace', 'Crime|Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (467, 'Time Without Pity', 'Crime|Drama|Mystery');
insert into MOVIES (movie_id, title, genre)values (468, 'Bonjour Monsieur Shlomi (Ha-Kochavim Shel Shlomi)', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (469, 'Cannibal! The Musical (a.k.a. Alferd Packer: The Musical)', 'Comedy|Horror|Musical|Western');
insert into MOVIES (movie_id, title, genre)values (470, 'Foolish Wives', 'Drama');
insert into MOVIES (movie_id, title, genre)values (471, 'Forbidden', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (472, 'Mating Habits of the Earthbound Human, The', 'Comedy|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (473, 'Joseph and the Amazing Technicolor Dreamcoat', 'Musical');
insert into MOVIES (movie_id, title, genre)values (474, 'Face of a Fugitive', 'Western');
insert into MOVIES (movie_id, title, genre)values (475, 'Caltiki the Undying Monster', 'Adventure|Horror|Sci-Fi|Thriller');
insert into MOVIES (movie_id, title, genre)values (476, 'My Ain Folk', 'Drama');
insert into MOVIES (movie_id, title, genre)values (477, 'Five Days One Summer', 'Drama');
insert into MOVIES (movie_id, title, genre)values (478, 'Sixth Sense, The', 'Drama|Horror|Mystery');
insert into MOVIES (movie_id, title, genre)values (479, 'I Am Ali', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (480, 'Zandalee', 'Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (481, 'French Minister, The (Quai d''Orsay)', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (482, 'Conspiracy, The', 'Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (483, '20 Seconds of Joy', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (484, 'November Man, The', 'Action|Crime|Thriller');
insert into MOVIES (movie_id, title, genre)values (485, 'Time to Love and a Time to Die, A', 'Drama|Romance|War');
insert into MOVIES (movie_id, title, genre)values (486, 'Waiting Women (Kvinnors väntan)', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (487, 'Abbott and Costello Meet Captain Kidd', 'Adventure|Comedy|Musical');
insert into MOVIES (movie_id, title, genre)values (488, 'Mighty Uke', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (489, 'Made in U.S.A.', 'Crime|Mystery');
insert into MOVIES (movie_id, title, genre)values (490, 'Death Race', 'Action|Adventure|Sci-Fi|Thriller');
insert into MOVIES (movie_id, title, genre)values (491, 'Horns', 'Horror|Mystery');
insert into MOVIES (movie_id, title, genre)values (492, 'American Carol, An', 'Comedy|Fantasy');
insert into MOVIES (movie_id, title, genre)values (493, 'Open Season', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (494, 'Better Luck Tomorrow', 'Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (495, 'Character (Karakter)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (496, 'Heart of Dragon (Long de xin)', 'Action|Comedy|Crime|Drama|War');
insert into MOVIES (movie_id, title, genre)values (497, 'Ride Lonesome', 'Western');
insert into MOVIES (movie_id, title, genre)values (498, 'Grant Morrison: Talking with Gods', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (499, 'Isle of the Dead', 'Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (500, 'Kite Runner, The', 'Drama');
insert into MOVIES (movie_id, title, genre)values (501, 'Conspiracy', 'Drama|War');
insert into MOVIES (movie_id, title, genre)values (502, 'Wolfsburg', 'Drama');
insert into MOVIES (movie_id, title, genre)values (503, 'Lara Croft: Tomb Raider', 'Action|Adventure');
insert into MOVIES (movie_id, title, genre)values (504, 'Christmas Story 2, A', 'Children|Comedy');
insert into MOVIES (movie_id, title, genre)values (505, 'Moon Zero Two', 'Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (506, 'Thor', 'Action|Adventure|Drama|Fantasy|IMAX');
insert into MOVIES (movie_id, title, genre)values (507, 'Art of Crying, The (Kunsten at græde i kor)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (508, 'Happiest Days of Your Life, The', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (509, 'Little Indian, Big City (Un indien dans la ville)', 'Adventure|Children|Comedy');
insert into MOVIES (movie_id, title, genre)values (510, 'Distant (Uzak)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (511, 'Prince of Jutland (a.k.a. Royal Deceit)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (512, 'Merrill''s Marauders', 'Adventure|Drama|War');
insert into MOVIES (movie_id, title, genre)values (513, 'Article 99', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (514, 'Strike! (a.k.a. All I Wanna Do, The Hairy Bird)', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (515, 'Kevin Hart: Seriously Funny', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (516, 'Guarding Tess', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (517, 'Lamp in the Dark; The Untold History of the Bible, A', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (518, 'They All Lie', 'Drama');
insert into MOVIES (movie_id, title, genre)values (519, 'Samaritan Girl (Samaria)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (520, 'Black Rain (Kuroi ame)', 'Drama|War');
insert into MOVIES (movie_id, title, genre)values (521, 'Hallam Foe (Mister Foe)', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (522, 'Billu', 'Comedy|Drama|Musical');
insert into MOVIES (movie_id, title, genre)values (523, '20 Years After', 'Drama|Fantasy|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (524, 'Black Cloud', 'Drama');
insert into MOVIES (movie_id, title, genre)values (525, 'Fuck', 'Comedy|Documentary');
insert into MOVIES (movie_id, title, genre)values (526, 'Public Sex', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (527, 'Clairvoyant, The', 'Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (528, 'At Berkeley', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (529, 'Retreat', 'Thriller');
insert into MOVIES (movie_id, title, genre)values (530, 'Diving In', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (531, 'Mumia Abu-Jamal: A Case for Reasonable Doubt?', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (532, 'Inbetweeners 2, The', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (533, 'Knick Knack', 'Animation|Children');
insert into MOVIES (movie_id, title, genre)values (534, 'Ladder 49', 'Action|Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (535, 'Deadly Outlaw: Rekka (a.k.a. Violent Fire) (Jitsuroku Andô Noboru kyôdô-den: Rekka)', 'Crime|Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (536, 'Experts, The', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (537, 'The Good Lie', 'Drama');
insert into MOVIES (movie_id, title, genre)values (538, 'Beast Must Die, The', 'Horror|Mystery');
insert into MOVIES (movie_id, title, genre)values (539, 'Faust', 'Drama|Fantasy|Horror');
insert into MOVIES (movie_id, title, genre)values (540, 'Het Vonnis', 'Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (541, 'Cinderella', 'Fantasy|Romance');
insert into MOVIES (movie_id, title, genre)values (542, 'Transit', 'Crime|Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (543, 'Scandali nudi', '(no genres listed)');
insert into MOVIES (movie_id, title, genre)values (544, 'Nutty Professor, The', 'Comedy|Fantasy|Romance|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (545, 'Little Fugitive', 'Drama');
insert into MOVIES (movie_id, title, genre)values (546, 'Happy People: A Year in the Taiga', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (547, 'Tempest', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (548, 'Lust, Caution (Se, jie)', 'Drama|Romance|Thriller|War');
insert into MOVIES (movie_id, title, genre)values (549, 'Arcade', 'Horror|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (550, 'Take Me Home', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (551, 'Cocoon: The Return', 'Comedy|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (552, 'Blacksmith, The', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (553, 'Angus, Thongs and Perfect Snogging', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (554, 'Sovereign''s Company', 'Drama');
insert into MOVIES (movie_id, title, genre)values (555, 'Major and the Minor, The', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (556, 'Beowulf & Grendel', 'Action|Adventure|Drama|Fantasy');
insert into MOVIES (movie_id, title, genre)values (557, 'Curb Dance', '(no genres listed)');
insert into MOVIES (movie_id, title, genre)values (558, 'Campaign, The', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (559, 'Exit Humanity', 'Drama|Horror');
insert into MOVIES (movie_id, title, genre)values (560, 'My Mom''s New Boyfriend', 'Action|Comedy|Romance|Thriller');
insert into MOVIES (movie_id, title, genre)values (561, 'Tabloid', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (562, 'Prince of Persia: The Sands of Time', 'Action|Adventure|Fantasy|Romance|IMAX');
insert into MOVIES (movie_id, title, genre)values (563, 'Stand Off', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (564, 'I Like It Like That', 'Comedy|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (565, 'Defiance', 'Drama|Thriller|War');
insert into MOVIES (movie_id, title, genre)values (566, 'Making a Killing: The Untold Story of Psychotropic Drugging', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (567, 'Dangerous Method, A', 'Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (568, 'Upswing (Nousukausi)', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (569, 'Something Borrowed', 'Comedy|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (570, 'Kung Fu Panda Holiday Special', 'Animation|Children|Comedy');
insert into MOVIES (movie_id, title, genre)values (571, 'Die! Die! My Darling! (Fanatic)', 'Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (572, 'Cut-Throats Nine (Condenados a vivir)', 'Crime|Thriller|Western');
insert into MOVIES (movie_id, title, genre)values (573, 'When the Road Bends: Tales of a Gypsy Caravan', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (574, 'Huey P. Newton Story, A', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (575, 'Street Thief', 'Crime|Documentary');
insert into MOVIES (movie_id, title, genre)values (576, 'Dark Command', 'Western');
insert into MOVIES (movie_id, title, genre)values (577, 'Pat and Mike', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (578, 'First Time, The', 'Comedy|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (579, 'Horde, The (La Horde)', 'Action|Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (580, 'Wee Willie Winkie', 'Adventure');
insert into MOVIES (movie_id, title, genre)values (581, 'Garden Lovers (Eedenistä pohjoiseen)', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (582, 'Roaring Twenties, The', 'Crime|Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (583, 'Back to 1942 ', 'Drama|IMAX');
insert into MOVIES (movie_id, title, genre)values (584, 'Final Conflict, The (a.k.a. Omen III: The Final Conflict)', 'Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (585, 'Lady in Cement', 'Crime|Drama|Mystery|Thriller');
insert into MOVIES (movie_id, title, genre)values (586, 'St. Trinian''s', 'Children|Comedy');
insert into MOVIES (movie_id, title, genre)values (587, 'Big Sur', 'Drama');
insert into MOVIES (movie_id, title, genre)values (588, 'One I Love, The', 'Comedy|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (589, 'Many Adventures of Winnie the Pooh, The', 'Animation|Children|Musical');
insert into MOVIES (movie_id, title, genre)values (590, 'Sons of Katie Elder', 'Western');
insert into MOVIES (movie_id, title, genre)values (591, 'Station West', 'Action|Mystery|Romance|Western');
insert into MOVIES (movie_id, title, genre)values (592, '2009: Lost Memories', 'Action|Sci-Fi|Thriller');
insert into MOVIES (movie_id, title, genre)values (593, 'Never Back Down', 'Action');
insert into MOVIES (movie_id, title, genre)values (594, 'Peacekeeper, The', 'Action');
insert into MOVIES (movie_id, title, genre)values (595, 'Crank: High Voltage', 'Action|Comedy|Crime');
insert into MOVIES (movie_id, title, genre)values (596, 'Thin Line Between Love and Hate, A', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (597, 'Keith', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (598, 'Maniac', 'Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (599, 'Lucky One, The', 'Drama');
insert into MOVIES (movie_id, title, genre)values (600, 'Happenstance (Battement d''ailes du papillon, Le)', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (601, 'Fame', 'Drama|Musical');
insert into MOVIES (movie_id, title, genre)values (602, 'Yesterday', 'Drama');
insert into MOVIES (movie_id, title, genre)values (603, 'Die Hard 2', 'Action|Adventure|Thriller');
insert into MOVIES (movie_id, title, genre)values (604, 'Poltergeist II: The Other Side', 'Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (605, 'Breed, The', 'Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (606, 'Biggles', 'Adventure|Fantasy|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (607, 'Before Midnight', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (608, 'Ice Castles', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (609, 'Waco: A New Revelation', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (610, 'The Menacing Eye', '(no genres listed)');
insert into MOVIES (movie_id, title, genre)values (611, 'Zatoichi Goes to the Fire Festival (Zatôichi abare-himatsuri) (Zatôichi 21)', 'Action|Drama');
insert into MOVIES (movie_id, title, genre)values (612, 'Universal Soldier: The Return', 'Action|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (613, 'Magnificent Seven Ride!, The', 'Western');
insert into MOVIES (movie_id, title, genre)values (614, 'Welcome Mr. Marshall (Bienvenido Mister Marshall)', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (615, 'National Lampoon''s Van Wilder: The Rise of Taj', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (616, 'Real McCoy, The', 'Action|Crime|Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (617, 'Nines, The', 'Drama|Mystery');
insert into MOVIES (movie_id, title, genre)values (618, 'After Last Season', 'Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (619, 'Allnighter, The', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (620, 'Nola', 'Drama');
insert into MOVIES (movie_id, title, genre)values (621, 'Do the Right Thing', 'Drama');
insert into MOVIES (movie_id, title, genre)values (622, 'Needful Things', 'Drama|Horror');
insert into MOVIES (movie_id, title, genre)values (623, 'Winter Kills', 'Drama');
insert into MOVIES (movie_id, title, genre)values (624, 'Party Monster', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (625, 'Liliom', 'Drama|Fantasy');
insert into MOVIES (movie_id, title, genre)values (626, 'Gruffalo, The', 'Adventure|Animation|Children|Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (627, 'Mission, The (Cheung fo)', 'Crime|Drama|Mystery');
insert into MOVIES (movie_id, title, genre)values (628, 'Best Seller', 'Thriller');
insert into MOVIES (movie_id, title, genre)values (629, 'Coming Apart', 'Drama');
insert into MOVIES (movie_id, title, genre)values (630, 'Our Idiot Brother', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (631, 'Bears', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (632, 'Just Anybody (Le premier venu)', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (633, 'Maya Lin: A Strong Clear Vision', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (634, 'Beverly Hills Chihuahua 2', 'Children|Comedy');
insert into MOVIES (movie_id, title, genre)values (635, 'Dead Bang', 'Thriller');
insert into MOVIES (movie_id, title, genre)values (636, 'Action in the North Atlantic', 'Action|War');
insert into MOVIES (movie_id, title, genre)values (637, 'North (Nord)', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (638, 'Hitting Home', 'Drama|Romance|Thriller');
insert into MOVIES (movie_id, title, genre)values (639, 'Life of Oharu, The (Saikaku ichidai onna)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (640, 'Red Army', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (641, 'Retroactive', 'Sci-Fi|Thriller');
insert into MOVIES (movie_id, title, genre)values (642, 'Amor?', 'Drama');
insert into MOVIES (movie_id, title, genre)values (643, 'To Gillian on Her 37th Birthday', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (644, 'Autumn Ball (Sügisball)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (645, 'Bugs Bunny''s 3rd Movie: 1001 Rabbit Tales', 'Adventure|Animation|Children|Comedy');
insert into MOVIES (movie_id, title, genre)values (646, 'Heaven & Earth', 'Action|Drama|War');
insert into MOVIES (movie_id, title, genre)values (647, 'Eila', 'Drama');
insert into MOVIES (movie_id, title, genre)values (648, 'Great Directors', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (649, 'Three Comrades', 'Drama');
insert into MOVIES (movie_id, title, genre)values (650, 'Mail Order Bride', 'Comedy|Western');
insert into MOVIES (movie_id, title, genre)values (651, 'Sergio', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (652, 'Sherman''s March', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (653, 'For the Bible Tells Me So', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (654, 'Finger, The (Dedo, El)', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (655, 'Ultraman (Chôhen kaijû eiga: Urutoraman)', 'Action|Fantasy|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (656, 'Daybreakers', 'Action|Drama|Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (657, 'Windstruck (Nae yeojachingureul sogae habnida)', 'Comedy|Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (658, 'Rise & Fall of ECW, The', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (659, 'Rise & Fall of ECW, The', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (660, 'Manslaughter (Drabet)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (661, 'Deception', 'Action');
insert into MOVIES (movie_id, title, genre)values (662, 'Reluctant Debutante, The', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (663, 'The Broken Jug', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (664, 'Patrick', 'Horror|Sci-Fi|Thriller');
insert into MOVIES (movie_id, title, genre)values (665, 'Golden Boy', 'Drama');
insert into MOVIES (movie_id, title, genre)values (666, 'Sleepaway Camp', 'Horror');
insert into MOVIES (movie_id, title, genre)values (667, 'Man About Town', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (668, 'Anchorman: The Legend of Ron Burgundy', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (669, 'Zero Tolerance (Noll tolerans)', 'Action|Crime|Thriller');
insert into MOVIES (movie_id, title, genre)values (670, 'Party, The (Boum, La)', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (671, 'Excision', 'Crime|Drama|Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (672, 'Cypher', 'Action|Sci-Fi|Thriller');
insert into MOVIES (movie_id, title, genre)values (673, 'Amour', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (674, 'Love Crime (Crime d''amour)', 'Crime|Mystery|Thriller');
insert into MOVIES (movie_id, title, genre)values (675, 'Final Destination', 'Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (676, 'My Name Is Bruce', 'Comedy|Horror');
insert into MOVIES (movie_id, title, genre)values (677, 'Romy and Michele: In the Beginning', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (678, 'Expect No Mercy', 'Action|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (679, 'Husbands', 'Drama');
insert into MOVIES (movie_id, title, genre)values (680, 'Shadow Company', 'Documentary|War');
insert into MOVIES (movie_id, title, genre)values (681, 'Star Witness, The', 'Drama');
insert into MOVIES (movie_id, title, genre)values (682, 'Phyllis and Harold', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (683, 'Zeitgeist: The Movie', 'Documentary|War');
insert into MOVIES (movie_id, title, genre)values (684, 'CB4 - The Movie', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (685, 'Garden Lovers (Eedenistä pohjoiseen)', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (686, 'The Last Station', 'Drama');
insert into MOVIES (movie_id, title, genre)values (687, 'Blood Trails ', 'Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (688, 'Abelar: Tales of an Ancient Empire (Tales of an Ancient Empire)', 'Fantasy');
insert into MOVIES (movie_id, title, genre)values (689, 'Happiness Is in the Field (Bonheur est dans le pré, Le)', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (690, 'Act of Violence', 'Drama|Film-Noir|Thriller');
insert into MOVIES (movie_id, title, genre)values (691, 'God Said ''Ha!''', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (692, 'Lion''s Den (Leonera)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (693, 'Brainstorm (Bicho de Sete Cabeças)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (694, 'Mall', 'Drama');
insert into MOVIES (movie_id, title, genre)values (695, 'Bells, The', 'Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (696, 'Birdcage Inn (Paran daemun)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (697, 'Head Games', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (698, 'Victim', 'Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (699, 'Heist', 'Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (700, 'Steamboat Bill, Jr.', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (701, 'Breaking Point', 'Thriller');
insert into MOVIES (movie_id, title, genre)values (702, 'Tony Arzenta (No Way Out) (Big Guns)', 'Action|Crime|Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (703, 'Cry_Wolf (a.k.a. Cry Wolf)', 'Drama|Horror|Mystery|Thriller');
insert into MOVIES (movie_id, title, genre)values (704, 'Sanjuro (Tsubaki Sanjûrô)', 'Action|Adventure|Drama');
insert into MOVIES (movie_id, title, genre)values (705, 'The Invisible Frame', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (706, 'First Kid', 'Children|Comedy');
insert into MOVIES (movie_id, title, genre)values (707, 'Down to the Sea in Ships', 'Drama');
insert into MOVIES (movie_id, title, genre)values (708, 'Tale of Princess Kaguya, The (Kaguyahime no monogatari)', 'Animation|Drama|Fantasy');
insert into MOVIES (movie_id, title, genre)values (709, 'Little Accidents', 'Drama');
insert into MOVIES (movie_id, title, genre)values (710, 'Something Real and Good', 'Drama');
insert into MOVIES (movie_id, title, genre)values (711, 'Tension', 'Crime|Drama|Film-Noir|Romance');
insert into MOVIES (movie_id, title, genre)values (712, 'I Wanna Hold Your Hand', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (713, 'Life On A String (Bian chang Bian Zou)', 'Adventure|Drama|Fantasy|Musical');
insert into MOVIES (movie_id, title, genre)values (714, 'Very Good Girls', 'Drama');
insert into MOVIES (movie_id, title, genre)values (715, 'Angel', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (716, 'Journey Into Fear', 'Drama|Film-Noir|War');
insert into MOVIES (movie_id, title, genre)values (717, 'For My Father (Sof Shavua B''Tel Aviv)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (718, 'Road Home, The (Wo de fu qin mu qin)', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (719, 'Place of One''s Own, A', 'Drama|Mystery|Thriller');
insert into MOVIES (movie_id, title, genre)values (720, 'Star of Midnight', 'Comedy|Mystery|Romance');
insert into MOVIES (movie_id, title, genre)values (721, 'Truth or Die ', 'Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (722, 'Day the Universe Changed, The', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (723, 'Mandela: Long Walk to Freedom', 'Drama');
insert into MOVIES (movie_id, title, genre)values (724, 'Fagbug', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (725, 'Agata and the Storm (Agata e la tempesta)', 'Comedy|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (726, 'Horrible Dr. Hichcock, The', 'Horror');
insert into MOVIES (movie_id, title, genre)values (727, 'Conflagration (Enjô)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (728, 'Mark, The', 'Drama');
insert into MOVIES (movie_id, title, genre)values (729, 'Pretty One, The', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (730, 'Tartuffe (Herr Tartüff)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (731, 'My Father and My Son (Babam ve oglum)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (732, 'Fever Pitch', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (733, 'Killer: A Journal of Murder', 'Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (734, 'Midnight in the Garden of Good and Evil', 'Crime|Drama|Mystery');
insert into MOVIES (movie_id, title, genre)values (735, 'Puccini for Beginners', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (736, 'Slave Girls (Prehistoric Women)', 'Adventure|Fantasy');
insert into MOVIES (movie_id, title, genre)values (737, 'Little Odessa', 'Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (738, 'Genocide (Konchû daisensô)', 'Horror|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (739, 'McHale''s Navy', 'Comedy|War');
insert into MOVIES (movie_id, title, genre)values (740, 'Let It Be', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (741, 'Craig Ferguson: A Wee Bit o'' Revolution', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (742, 'Momma''s Man', 'Drama');
insert into MOVIES (movie_id, title, genre)values (743, 'Broken Bridges', 'Drama');
insert into MOVIES (movie_id, title, genre)values (744, 'Le crocodile du Botswanga', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (745, 'Women, The', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (746, 'Flying Fleet, The', 'Adventure|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (747, 'Leontine', 'Comedy|Crime');
insert into MOVIES (movie_id, title, genre)values (748, 'One Night Stand', 'Drama');
insert into MOVIES (movie_id, title, genre)values (749, 'Road, The', 'Adventure|Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (750, 'Now and Forever', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (751, 'Kummeli Goldrush (Kummeli kultakuume)', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (752, 'Sut (Milk)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (753, 'Snakes on a Plane', 'Action|Comedy|Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (754, 'Fat, Sick & Nearly Dead', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (755, 'Madagascar', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (756, 'Halo 4: Forward Unto Dawn', 'Action|Sci-Fi|Thriller');
insert into MOVIES (movie_id, title, genre)values (757, 'Friday', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (758, 'Return to House on Haunted Hill', 'Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (759, 'Last Mistress, The (vieille maîtresse, Une)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (760, 'The Fox & the Child', 'Adventure|Children|Drama');
insert into MOVIES (movie_id, title, genre)values (761, 'Prisoner of Zenda, The', 'Adventure');
insert into MOVIES (movie_id, title, genre)values (762, 'José and Pilar (José e Pilar)', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (763, 'Guy and a Gal, A (En kille och en tjej)', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (764, 'Paycheck', 'Action|Sci-Fi|Thriller');
insert into MOVIES (movie_id, title, genre)values (765, 'Hamlet', 'Drama');
insert into MOVIES (movie_id, title, genre)values (766, 'Chiedimi se sono felice', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (767, 'Venus Boyz', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (768, 'Downhill', 'Drama');
insert into MOVIES (movie_id, title, genre)values (769, 'Memories of Underdevelopment (Memorias del subdesarrollo)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (770, 'White Palms (Fehér tenyér)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (771, 'Evilspeak', 'Horror|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (772, 'Victor/Victoria', 'Comedy|Musical|Romance');
insert into MOVIES (movie_id, title, genre)values (773, 'By the Sea', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (774, 'Tracers', 'Action');
insert into MOVIES (movie_id, title, genre)values (775, 'On Borrowed Time', 'Comedy|Drama|Fantasy');
insert into MOVIES (movie_id, title, genre)values (776, 'Suspect X (Yôgisha X no kenshin)', 'Crime|Drama|Mystery');
insert into MOVIES (movie_id, title, genre)values (777, 'To Die Like a Man (Morrer Como Um Homem)', 'Drama|Fantasy|Musical');
insert into MOVIES (movie_id, title, genre)values (778, 'Red Chapel, The (Røde kapel, Det)', 'Comedy|Documentary');
insert into MOVIES (movie_id, title, genre)values (779, 'What Dreams May Come', 'Adventure|Drama|Fantasy|Romance');
insert into MOVIES (movie_id, title, genre)values (780, 'Anywhere But Here', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (781, 'The Hatchet Man', 'Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (782, 'Fat Kid Rules the World', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (783, 'Dead Outside, The', 'Horror|Mystery|Thriller');
insert into MOVIES (movie_id, title, genre)values (784, 'Interview with the Assassin', 'Drama');
insert into MOVIES (movie_id, title, genre)values (785, 'Illusionist, The', 'Drama|Fantasy|Mystery|Romance');
insert into MOVIES (movie_id, title, genre)values (786, 'Guy and a Gal, A (En kille och en tjej)', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (787, 'Zen', 'Drama');
insert into MOVIES (movie_id, title, genre)values (788, 'Big Mommas: Like Father, Like Son', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (789, 'Torrid Zone', 'Action|Adventure|Comedy');
insert into MOVIES (movie_id, title, genre)values (790, 'Blind Dating', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (791, 'Dr. Jekyll and Mr. Hyde', 'Drama|Horror');
insert into MOVIES (movie_id, title, genre)values (792, 'House', 'Drama|Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (793, 'Sex Tape', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (794, 'Big Parade, The', 'Drama|Romance|War');
insert into MOVIES (movie_id, title, genre)values (795, 'Air Doll (Kûki ningyô)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (796, 'Twelve Tasks of Asterix, The (Les douze travaux d''Astérix)', 'Action|Adventure|Animation|Children|Comedy|Fantasy');
insert into MOVIES (movie_id, title, genre)values (797, 'Dead Man Running', 'Action|Crime|Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (798, 'Short Film About John Bolton, A', 'Fantasy|Horror|Mystery');
insert into MOVIES (movie_id, title, genre)values (799, 'Billy the Kid vs. Dracula', 'Action|Drama|Horror');
insert into MOVIES (movie_id, title, genre)values (800, 'Paranoia', 'Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (801, 'Piripäiväkirja', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (802, 'Ironclads', 'Drama|Romance|War');
insert into MOVIES (movie_id, title, genre)values (803, 'Forced Vengeance', 'Action|Adventure');
insert into MOVIES (movie_id, title, genre)values (804, 'Rudderless', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (805, 'Mickey''s The Prince and the Pauper', 'Animation|Children');
insert into MOVIES (movie_id, title, genre)values (806, 'Servant, The', 'Drama');
insert into MOVIES (movie_id, title, genre)values (807, 'Alpha and Omega 2: A Howl-iday Adventure (Alpha & Omega 2)', 'Action|Adventure|Animation|Children|Comedy');
insert into MOVIES (movie_id, title, genre)values (808, 'Girl Who Talked to Dolphins, The', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (809, 'Abbott and Costello Meet Frankenstein', 'Comedy|Horror');
insert into MOVIES (movie_id, title, genre)values (810, 'Slipstream', 'Comedy|Drama|Fantasy|Mystery|Sci-Fi|Thriller');
insert into MOVIES (movie_id, title, genre)values (811, 'Querelle', 'Drama');
insert into MOVIES (movie_id, title, genre)values (812, 'Brass Teapot, The', 'Comedy|Fantasy|Thriller');
insert into MOVIES (movie_id, title, genre)values (813, 'Batman: Mask of the Phantasm', 'Animation|Children');
insert into MOVIES (movie_id, title, genre)values (814, 'To the Left of the Father (Lavoura Arcaica)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (815, 'Band''s Visit, The (Bikur Ha-Tizmoret)', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (816, 'Spriggan (Supurigan)', 'Action|Animation|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (817, 'Battle of Britain, The (Why We Fight, 4)', 'Documentary|War');
insert into MOVIES (movie_id, title, genre)values (818, 'None But the Lonely Heart', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (819, 'City of Violence, The (Jjakpae)', 'Action|Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (820, 'Mar Baum', 'Drama');
insert into MOVIES (movie_id, title, genre)values (821, 'Tai Chi Zero', 'Action|Fantasy|Sci-Fi|IMAX');
insert into MOVIES (movie_id, title, genre)values (822, 'No habrá paz para los malvados', 'Film-Noir|Thriller');
insert into MOVIES (movie_id, title, genre)values (823, 'Angel', 'Action|Crime|Thriller');
insert into MOVIES (movie_id, title, genre)values (824, 'Champion', 'Drama|Film-Noir|Romance');
insert into MOVIES (movie_id, title, genre)values (825, 'Funny Girl', 'Drama|Musical|Romance');
insert into MOVIES (movie_id, title, genre)values (826, 'Living Death', 'Drama|Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (827, 'Die Is Cast, The (La suerte está echada)', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (828, 'Aujourd''hui', 'Drama');
insert into MOVIES (movie_id, title, genre)values (829, 'Diary of a Chambermaid (Journal d''une femme de chambre, Le)', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (830, 'Without Love', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (831, 'Thing from Another World, The', 'Horror|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (832, 'In This Our Life', 'Drama');
insert into MOVIES (movie_id, title, genre)values (833, 'Chimpanzee', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (834, 'Stingray Sam', 'Comedy|Musical|Sci-Fi|Western');
insert into MOVIES (movie_id, title, genre)values (835, 'Spring is Here', 'Comedy|Musical|Romance');
insert into MOVIES (movie_id, title, genre)values (836, 'Thursday', 'Action|Crime|Thriller');
insert into MOVIES (movie_id, title, genre)values (837, 'Grand Canyon', 'Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (838, 'Beautiful Boxer', 'Action|Drama');
insert into MOVIES (movie_id, title, genre)values (839, 'A.C.O.D.', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (840, 'Afternoon of a Torturer, The (Dupa-amiaza unui tortionar)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (841, 'Meet Bill', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (842, 'Django 2: Django Strikes Again', 'Western');
insert into MOVIES (movie_id, title, genre)values (843, 'Spiders Part 1: The Golden Lake, The (Die Spinnen, 1. Teil: Der Goldene See)', 'Action|Adventure|Drama');
insert into MOVIES (movie_id, title, genre)values (844, 'Haiku Tunnel', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (845, 'Mercy Streets', 'Action|Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (846, 'Jack the Giant Killer', 'Action|Fantasy');
insert into MOVIES (movie_id, title, genre)values (847, 'Friend Among Strangers, Stranger Among Friends (Svoy sredi chuzhikh, chuzhoy sredi svoikh)', 'Action|War|Western');
insert into MOVIES (movie_id, title, genre)values (848, 'Big Knife, The', 'Film-Noir');
insert into MOVIES (movie_id, title, genre)values (849, 'Necessary Death, A', 'Crime|Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (850, 'La petite reine', 'Drama');
insert into MOVIES (movie_id, title, genre)values (851, 'Octopussy', 'Action|Adventure|Thriller');
insert into MOVIES (movie_id, title, genre)values (852, 'Shepherd: Border Patrol, The', 'Action|Crime|Thriller');
insert into MOVIES (movie_id, title, genre)values (853, 'Secrets of Jonathan Sperry, The', 'Drama');
insert into MOVIES (movie_id, title, genre)values (854, 'Advance to the Rear', 'Comedy|War|Western');
insert into MOVIES (movie_id, title, genre)values (855, 'Get Out Your Handkerchiefs (Préparez vos mouchoirs)', 'Comedy|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (856, 'Salinger', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (857, 'Benny & Joon', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (858, 'Milwaukee, Minnesota', 'Drama');
insert into MOVIES (movie_id, title, genre)values (859, '41', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (860, 'Big Picture, The (L''homme qui voulait vivre sa vie)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (861, 'Wanda', 'Drama');
insert into MOVIES (movie_id, title, genre)values (862, 'Trash', 'Adventure|Crime|Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (863, 'Blue', 'Romance|Western');
insert into MOVIES (movie_id, title, genre)values (864, 'Genesis', 'Drama|Horror');
insert into MOVIES (movie_id, title, genre)values (865, 'Scooby-Doo 2: Monsters Unleashed', 'Action|Adventure|Children|Comedy|Mystery');
insert into MOVIES (movie_id, title, genre)values (866, 'Bravados, The', 'Drama|Western');
insert into MOVIES (movie_id, title, genre)values (867, 'In the Valley of Elah', 'Drama|Mystery');
insert into MOVIES (movie_id, title, genre)values (868, 'Nomads', 'Horror|Mystery|Thriller');
insert into MOVIES (movie_id, title, genre)values (869, 'Annie Hall', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (870, 'Palookaville', 'Action|Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (871, 'Crossfire Trail (Louis L''Amour''s ''Crossfire Trail'')', 'Action|Western');
insert into MOVIES (movie_id, title, genre)values (872, 'Grave Encounters', 'Horror');
insert into MOVIES (movie_id, title, genre)values (873, 'Wu Tang Master (Tian shi zhuang xie)', 'Action');
insert into MOVIES (movie_id, title, genre)values (874, 'Forest (Rengeteg)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (875, 'Personal Velocity', 'Drama');
insert into MOVIES (movie_id, title, genre)values (876, 'Susan Slept Here', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (877, 'Boyz N the Hood', 'Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (878, 'Ingeborg Holm', 'Drama');
insert into MOVIES (movie_id, title, genre)values (879, 'Glumov''s Diary (Dnevnik Glumova)', '(no genres listed)');
insert into MOVIES (movie_id, title, genre)values (880, 'Break-Up, The', 'Comedy|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (881, 'Riley Rewind', 'Drama|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (882, 'Bad and the Beautiful, The', 'Drama');
insert into MOVIES (movie_id, title, genre)values (883, 'Peggy Sue Got Married', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (884, 'Visitors', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (885, 'Into the Blue 2: The Reef', 'Action|Adventure|Thriller');
insert into MOVIES (movie_id, title, genre)values (886, 'Ruby Cairo', 'Thriller');
insert into MOVIES (movie_id, title, genre)values (887, 'Octagon, The', 'Action');
insert into MOVIES (movie_id, title, genre)values (888, 'Alibi, The (Lies and Alibis)', 'Comedy|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (889, 'Ricky Rapper and the Bicycle Thief (Risto Räppääjä ja polkupyörävaras)', 'Children|Comedy|Musical');
insert into MOVIES (movie_id, title, genre)values (890, 'Kiss of the Damned', 'Horror|Romance|Thriller');
insert into MOVIES (movie_id, title, genre)values (891, 'About Alex', 'Drama');
insert into MOVIES (movie_id, title, genre)values (892, 'Any Day Now', 'Drama');
insert into MOVIES (movie_id, title, genre)values (893, 'Here Comes Mr. Jordan', 'Comedy|Fantasy|Romance');
insert into MOVIES (movie_id, title, genre)values (894, 'Legend, The (Legend of Fong Sai-Yuk, The) (Fong Sai Yuk)', 'Action|Comedy');
insert into MOVIES (movie_id, title, genre)values (895, 'Fairy, The (La fée) ', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (896, 'Samson & Sally', 'Animation|Children|Romance');
insert into MOVIES (movie_id, title, genre)values (897, 'Woman''s Tale, A', 'Drama');
insert into MOVIES (movie_id, title, genre)values (898, 'Barbershop', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (899, 'Helter Skelter', 'Crime|Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (900, 'Object of My Affection, The', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (901, 'Ennui, L''', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (902, 'The Referee', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (903, 'Catacombs', 'Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (904, 'Darktown Strutters (Get Down and Boogie)', 'Action|Comedy|Musical');
insert into MOVIES (movie_id, title, genre)values (905, 'Kiss the Girls', 'Crime|Drama|Mystery|Thriller');
insert into MOVIES (movie_id, title, genre)values (906, 'Along the Ridge (Anche libero va bene)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (907, 'Eklavya: The Royal Guard', 'Action|Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (908, 'Commune, La (Paris, 1871)', 'Drama|War');
insert into MOVIES (movie_id, title, genre)values (909, 'Truth or Consequences, N.M.', 'Action|Crime|Romance');
insert into MOVIES (movie_id, title, genre)values (910, 'Friday', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (911, 'Tarnation', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (912, 'Paths of Glory', 'Drama|War');
insert into MOVIES (movie_id, title, genre)values (913, 'Richard Pryor Here and Now', 'Comedy|Documentary');
insert into MOVIES (movie_id, title, genre)values (914, '8 Seconds', 'Drama');
insert into MOVIES (movie_id, title, genre)values (915, 'Fast and the Furious, The', 'Crime|Mystery');
insert into MOVIES (movie_id, title, genre)values (916, 'Django Unchained', 'Action|Drama|Western');
insert into MOVIES (movie_id, title, genre)values (917, 'Prefontaine', 'Drama');
insert into MOVIES (movie_id, title, genre)values (918, 'See Here, Private Hargrove', 'Comedy|Romance|War');
insert into MOVIES (movie_id, title, genre)values (919, 'Brothers Lionheart, The (Bröderna Lejonhjärta)', 'Adventure|Children|Fantasy');
insert into MOVIES (movie_id, title, genre)values (920, 'Search for One-eye Jimmy, The', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (921, 'Contact', 'Drama|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (922, 'Zandalee', 'Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (923, 'The Little Death', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (924, 'Future Cops (Chao ji xue xiao ba wang)', 'Action');
insert into MOVIES (movie_id, title, genre)values (925, 'Brick', 'Crime|Drama|Film-Noir|Mystery');
insert into MOVIES (movie_id, title, genre)values (926, 'Supercondriaque', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (927, 'Jane Austen Book Club, The', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (928, 'Playing ''In the Company of Men'' (En jouant ''Dans la compagnie des hommes'')', 'Drama');
insert into MOVIES (movie_id, title, genre)values (929, 'Mr. Sardonicus', 'Horror');
insert into MOVIES (movie_id, title, genre)values (930, 'City in the Sea', 'Adventure|Fantasy|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (931, 'Perfect', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (932, 'Gasht-e ershad', 'Comedy|Crime|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (933, 'Burrowers, The', 'Horror|Thriller|Western');
insert into MOVIES (movie_id, title, genre)values (934, 'Red', 'Action|Comedy');
insert into MOVIES (movie_id, title, genre)values (935, 'Oranges, The', 'Comedy|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (936, 'Hell''s Gate 11:11', 'Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (937, 'Twixt', 'Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (938, 'Japanese Summer: Double Suicide (Muri shinjû: Nihon no natsu)', 'Crime|Drama');
insert into MOVIES (movie_id, title, genre)values (939, 'Blood, Guts, Bullets and Octane', 'Action|Comedy');
insert into MOVIES (movie_id, title, genre)values (940, 'Through the Forest', 'Drama');
insert into MOVIES (movie_id, title, genre)values (941, 'High School', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (942, 'Chris Rock: Bring the Pain', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (943, 'Psycho', 'Crime|Horror');
insert into MOVIES (movie_id, title, genre)values (944, 'Ski School', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (945, 'Urbania', 'Drama');
insert into MOVIES (movie_id, title, genre)values (946, 'Sawdust and Tinsel (Gycklarnas afton)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (947, 'Man Next Door, The (El hombre de al lado)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (948, 'Day''s Pleasure, A (Ford Story, A)', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (949, 'Shinjuku Incident (San suk si gin)', 'Crime|Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (950, 'Johnny Mnemonic', 'Action|Sci-Fi|Thriller');
insert into MOVIES (movie_id, title, genre)values (951, 'Legend of Lizzie Borden, The', 'Drama');
insert into MOVIES (movie_id, title, genre)values (952, 'Big', 'Comedy|Drama|Fantasy|Romance');
insert into MOVIES (movie_id, title, genre)values (953, 'Story of Women (Affaire de femmes, Une)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (954, 'One Flew Over the Cuckoo''s Nest', 'Drama');
insert into MOVIES (movie_id, title, genre)values (955, 'Confessions of a Pop Performer', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (956, 'Flying Fleet, The', 'Adventure|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (957, 'Big Green, The', 'Children|Comedy');
insert into MOVIES (movie_id, title, genre)values (958, 'Subspecies', 'Horror');
insert into MOVIES (movie_id, title, genre)values (959, 'Story of Seabiscuit, The', 'Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (960, 'Cell 2, The', 'Horror|Sci-Fi|Thriller');
insert into MOVIES (movie_id, title, genre)values (961, 'Mighty Morphin Power Rangers: The Movie', 'Action|Children');
insert into MOVIES (movie_id, title, genre)values (962, 'Hole in the Head, A', 'Comedy|Musical');
insert into MOVIES (movie_id, title, genre)values (963, 'Cabinet of Dr. Caligari, The (Cabinet des Dr. Caligari., Das)', 'Crime|Fantasy|Horror');
insert into MOVIES (movie_id, title, genre)values (964, 'Centenarian Who Climbed Out the Window and Vanished, The (Hundraåringen som klev ut genom fönstret och försvann)', 'Adventure|Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (965, 'Beauty and the Beast', 'Animation|Children|Fantasy|Musical|Romance|IMAX');
insert into MOVIES (movie_id, title, genre)values (966, 'First Power, The', 'Crime|Horror|Thriller');
insert into MOVIES (movie_id, title, genre)values (967, 'There''s Always Tomorrow', 'Drama');
insert into MOVIES (movie_id, title, genre)values (968, 'More Than a Game', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (969, 'Happythankyoumoreplease', 'Comedy|Drama');
insert into MOVIES (movie_id, title, genre)values (970, 'Moonbase', 'Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (971, 'From the Terrace', 'Drama');
insert into MOVIES (movie_id, title, genre)values (972, 'That Night in Varennes (Nuit de Varennes, La)', 'Drama');
insert into MOVIES (movie_id, title, genre)values (973, 'Hiding Place, The', 'Drama|War');
insert into MOVIES (movie_id, title, genre)values (974, 'Ready to Rumble', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (975, 'Hatful of Rain, A', 'Drama');
insert into MOVIES (movie_id, title, genre)values (976, 'Werewolf Boy, A (Neuk-dae-so-nyeon)', 'Drama|Fantasy|Romance');
insert into MOVIES (movie_id, title, genre)values (977, 'Real McCoy, The', 'Drama');
insert into MOVIES (movie_id, title, genre)values (978, 'Plácido', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (979, 'Mary Shelley''s Frankenstein (Frankenstein)', 'Drama|Horror|Sci-Fi');
insert into MOVIES (movie_id, title, genre)values (980, 'Changing Lanes', 'Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (981, 'Dolphin Tale', 'Children|Drama');
insert into MOVIES (movie_id, title, genre)values (982, 'Rabbit Test', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (983, 'Waking Ned Devine (a.k.a. Waking Ned)', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (984, 'I Shot Andy Warhol', 'Drama');
insert into MOVIES (movie_id, title, genre)values (985, 'Big Fat Liar', 'Children|Comedy');
insert into MOVIES (movie_id, title, genre)values (986, 'Some Days Are Better Than Others', 'Drama');
insert into MOVIES (movie_id, title, genre)values (987, 'SuperBabies: Baby Geniuses 2', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (988, '10 Things I Hate About You', 'Comedy|Romance');
insert into MOVIES (movie_id, title, genre)values (989, 'Hamlet', 'Drama');
insert into MOVIES (movie_id, title, genre)values (990, 'Leprechaun', 'Comedy|Horror');
insert into MOVIES (movie_id, title, genre)values (991, 'Month in the Country, A', 'Drama');
insert into MOVIES (movie_id, title, genre)values (992, 'Misconception', 'Documentary');
insert into MOVIES (movie_id, title, genre)values (993, 'Great Locomotive Chase, The', 'Adventure|War');
insert into MOVIES (movie_id, title, genre)values (994, 'Dark Tide', 'Adventure|Drama|Thriller');
insert into MOVIES (movie_id, title, genre)values (995, 'Madison Avenue', 'Drama');
insert into MOVIES (movie_id, title, genre)values (996, 'Tokio Baby', 'Drama');
insert into MOVIES (movie_id, title, genre)values (997, 'Sitter, The', 'Comedy');
insert into MOVIES (movie_id, title, genre)values (998, 'In Old Chicago', 'Action|Drama|Musical|War');
insert into MOVIES (movie_id, title, genre)values (999, 'Man Who Sued God, The', 'Comedy|Drama|Romance');
insert into MOVIES (movie_id, title, genre)values (1000, 'Paris Is Burning', 'Documentary');

commit ;